services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: em_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: effective-mobile
    ports:
      - "5432:5432"

  subscription-service:
    image: golang:1.24-alpine
    command: sh -c "go run ./cmd/migrate/main.go && go run ./cmd/main.go"
    restart: unless-stopped
    working_dir: /subscription-service
    volumes:
      - .:/subscription-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres